blocks:
  STONE: 0.10
  COAL_ORE: 0.30
  REDSTONE_ORE: 0.40
  LAPIS_ORE: 0.50
  DIAMOND_ORE: 1.00
  EMERALD_ORE: 1.50
  # Ajoute ici des blocs et leur xp
smelts:
  IRON_INGOT: 0.50
  GOLD_INGOT: 0.70
  # Ajoute ici d'autres items cuits et leur xp
shop_sells:
  DIAMOND: 1.0    # 1 XP par diamant vendu
  IRON_INGOT: 0.2 # 0.2 XP par lingot vendu
  # etc.
mobs:
  ZOMBIE:
    xp: 5
    chance: 50  # pourcent (0-100)
  SKELETON:
    xp: 7
    chance: 15
  CREEPER:
    xp: 10
    chance: 5
  ENDERMAN:
    xp: 12
    chance: 100

enchant_rewards:
  '1-10': 10
  '11-15': 20
  '16-25': 25
  '26-30': 45

anvil_rewards:
  '1-5': 5
  '6-10': 10
  '11-15': 20
  '16-40': 45
