blocks:
  STONE: 0.10
  COAL_ORE: 0.30
  REDSTONE_ORE: 0.40
  LAPIS_ORE: 0.50
  DIAMOND_ORE: 15.00
  EMERALD_ORE: 25.00
  # Ajoute ici des blocs et leur xp
smelts:
  IRON_INGOT: 0.50
  GOLD_INGOT: 0.70
  # Ajoute ici d'autres items cuits et leur xp
shop_sells:
  DIAMOND: 1.0    # 1 XP par diamant vendu
  IRON_INGOT: 0.2 # 0.2 XP par lingot vendu
  # etc.
mobs:
  # Passifs
  CHICKEN:
    xp: 1
    chance: 50
  COW:
    xp: 2
    chance: 50
  PIG:
    xp: 2
    chance: 50
  SHEEP:
    xp: 2
    chance: 50
  RABBIT:
    xp: 5
    chance: 40
  MOOSHROOM:
    xp: 3
    chance: 40


  # Hostiles Overworld
  ZOMBIE:
    xp: 5
    chance: 50
  SPIDER:
    xp: 1
    chance: 30
  SKELETON:
    xp: 7
    chance: 20
  CREEPER:
    xp: 50
    chance: 5
  ENDERMAN:
    xp: 100
    chance: 100
  CAVE_SPIDER:
    xp: 2
    chance: 25
  WITCH:
    xp: 20
    chance: 5

  # Nether
  BLAZE:
    xp: 20
    chance: 10
  ZOMBIE_PIGMAN:
    xp: 10
    chance: 25



enchant_rewards:
  '1-10': 10
  '11-15': 15
  '16-25': 25
  '26-30': 35

anvil_rewards:
  '1-5': 5
  '6-10': 10
  '11-15': 20
  '16-40': 45

## PVP ##
kill_xp: 100

## FARM ##
crops:
  WHEAT: 5.0         # = CROPS quand mûr
  CARROT: 5.0        # = CARROT quand mûr
  POTATO: 5.0        # = POTATO quand mûr
  NETHER_WARTS: 6.0  # = NETHER_WARTS stade 3
  MELON_BLOCK: 8.0   # pastèque générée
  PUMPKIN: 8.0       # citrouille générée
  COCOA: 4.0
  SUGAR_CANE_BLOCK: 3.0
  CACTUS: 3.0

fishing_loots:
  RAW_FISH-0: 5.0   # Cod/Morue
  RAW_FISH-1: 8.0   # Saumon
  RAW_FISH-2: 15.0  # Poisson-globe
  RAW_FISH-3: 12.0  # Poisson tropical
  ENCHANTED_BOOK: 15.0
  NAME_TAG: 12.0
  SADDLE: 8.0
  BOW: 7.0
  FISHING_ROD: 6.0
  LEATHER: 2.0
  LEATHER_BOOTS: 2.5
  STICK: 1.0
  STRING: 2.0
  BOWL: 1.0
  GLASS_BOTTLE: 1.5
  BONE: 2.5
  INK_SACK: 2.5
  TRIPWIRE_HOOK: 2.0
  ROTTEN_FLESH: 1.0
  POTION: 2.5
  LILY_PAD: 3.0
