name: DrakariaProfile
main: fr.drakariaprofile.DrakariaProfile
version: 1.0
api-version: 1.8
author: Tokzeen
commands:
  quete_facile:
    description: "Ouvre les quêtes faciles"
  quete_moyen:
    description: "Ouvre les quêtes moyennes"
  quete_difficile:
    description: "Ouvre les quêtes difficiles"
  objectifs:
    description: "Menu Objectifs/Quêtes"
  objectif:
    description: "Menu Objectifs/Quêtes"
  quest:
    description: "Menu Objectifs/Quêtes"
  quests:
    description: "Menu Objectifs/Quêtes"
  quetes:
    description: "Menu Objectifs/Quêtes"
  rewards:
    description: "Menu des récompenses"
  reward:
    description: "Menu des récompenses"
  recompence:
    description: "Menu des récompenses"
  récompenses:
    description: "Menu des récompenses"
  drakariaProfile:
    description: "Commandes de profil"
  drakariaprofile:
    description: "Commandes de profil"
  profile:
    description: "Voir un profil"
permissions:
  drakariaprofile.admin:
    description: Accès admin à la commande drakariaProfile
    default: op
softdepend: [ShopGUIPlus]
