name: DrakariaProfile
main: fr.drakariaprofile.DrakariaProfile
version: 1.0
api-version: 1.8
author: Tokzeen
commands:
  profile:
    description: Voir le profil d’un joueur (ou soi)
  drakariaProfile:
    description: Commandes admin du plugin
  rewards:
    description: Ouvre le menu récompenses
  reward:
      aliases: [ rewards ]
      description: Alias reward
  récompenses:
    aliases: [rewards]
    description: Alias récompenses
  recompence:
    aliases: [rewards]
    description: Alias récompenses/fr
permissions:
  drakariaprofile.admin:
    description: Accès admin à la commande drakariaProfile
    default: op
softdepend: [ShopGUIPlus]
